Select * from table_name	

--Q1. What is the total revenue  generated by male vs female customers?
select gender, sum(purchase_amt) as total_revenue from table_name
group by gender

--Q2. Which customer used a discount but still spent more than the avg purchase amt?
select customer_id, purchase_amt, discount_applied from table_name
where discount_applied = 'Yes' and purchase_amt>=(select AVG(purchase_amt) from table_name)

--Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, avg(review_rating) as avg_review_rating from table_name
group by  item_purchased
order by avg_review_rating desc;

--Q4. Compare the average Purchase amounts between Standard and Express shipping?
Select shipping_type, AVG(purchase_amt) as avg_purchase_amt from table_name
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do. Subscribed customers spend more ? Comapre average spend and total revenue between subscribers and non- subscribers?
select subscription_status, count(customer_id)total_cust,AVG(purchase_amt)avg_purchase_amt, sum(purchase_amt)total_revenue from table_name
where subscription_status in ('Yes','No')
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discount applied?
select top 5 item_purchased,ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) as discount_rate  from table_name
group by item_purchased
order by discount_rate desc

--Q7.  Segment customers into new, Returning, and loyal based on their total number of previous purchases, and show the count of each segment?
with cust_type as 
(select customer_id, previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then  'Returning'
else 'Loyal' end as cust_segment
from table_name)
select cust_segment , count(*) as Nuber_of_Customers from cust_type
group by cust_segment

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select item_purchased, category ,count(*)as total_cust, ROW_NUMBER() over (partition by category order by count(*) desc) as item_rank from table_name
group by item_purchased, category)
select item_rank, category, item_purchased, total_cust
from item_counts
where item_rank <=3

--Q9. Are customers who are repeat buyers (more than 5 previous purcahses) also likely to subscribe?
select count(customer_id) as total_cust, subscription_status from table_name
where previous_purchases>5
group by subscription_status
order by total_cust

--Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amt) as revenue_contribution from table_name
group by age_group 
order by revenue_contribution desc